<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>dev.flyfish</groupId>
    <artifactId>passguard-parent</artifactId>
    <version>2.1.0</version>
  </parent>
  <artifactId>passguard-bom</artifactId>
  <packaging>pom</packaging>
  <name>PassGuard BOM</name>
  <description>PassGuard 组件版本清单</description>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard-generator</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard-password-hash</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard-crypto-core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard-crypto-jackson</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard-crypto-mybatis</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard-crypto-jpa-javax</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard-crypto-jpa-jakarta</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard-crypto-r2dbc-boot2</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard-crypto-r2dbc-boot3</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard-spring-boot2-starter</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.flyfish</groupId>
        <artifactId>passguard-spring-boot3-starter</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
